import Sidebar from '@/components/Sidebar'
import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import {Providers} from "./providers";
import Player from '@/components/Player';
import Main from '@/components/Main';

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <div className='flex h-[calc(100%-80px)]'>
            <Sidebar />
            <Main>
              {children}
            </Main>
          </div>
          <Player />
        </Providers>
      </body>
    </html>
  )
}
